# Generated by Django 3.2.12 on 2022-04-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espectador',
            name='name',
            field=models.CharField(default='Sin nombre', max_length=30),
        ),
        migrations.AlterField(
            model_name='creador',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='espectador',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='age',
            field=models.IntegerField(),
        ),
    ]
