# Generated by Django 3.2.12 on 2022-05-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profiledata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledata',
            old_name='description',
            new_name='Descripción',
        ),
        migrations.RenameField(
            model_name='profiledata',
            old_name='link',
            new_name='Link',
        ),
    ]
