# Generated by Django 3.2.12 on 2022-05-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_mensajes_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='mensaje',
            field=models.CharField(max_length=2000),
        ),
    ]
